CREATE TABLE memberSessions (
  idxNum SERIAL PRIMARY KEY,
  uID CHAR(32) NOT NULL,
  sID CHAR(32) NOT NULL,
  dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (uID),
  UNIQUE (sID)
);
